server:
  port: 8888

logging:
  path: logs
  file: userManger.log


spring:
  application:
    name: mytest
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.70.42:1521/orcl
    username: hndb_test_s1
    password: hndb_test_s1


mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

